name: deploy_to_gh_pages
on:
  push:
    branches: 
      - main

jobs:
  build_dist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: |
          npm i
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist_artifact
          path: dist/**/*
  
  deploy_dist:
    runs-on: ubuntu-20.04
    needs: build_dist
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - run: rm -rf ./*

      - uses: actions/download-artifact@v3
        with:
          name: dist_artifact
          path: ./

      - run: |
          ## Uncomment if deploying with custom domain enabled in your repo's GitHub pages settings. Must match your (sub)domain name
          echo "mickey.coffee" > CNAME
          git config --local user.email "posts_hook@github.com"
          git config --local user.name "Posts Hook"
          git add .
          git commit -m "[CI:deploy] deploy_dist job"

      - uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}